version: '3'
services:
  db:
    image: postgres:11-alpine
    restart: always
    ports:
      - '5432:5432'

  webpacker:
    build: .
    volumes:
      - .:/var/www/app
    ports:
      - '3035:3035'
    depends_on:
      - db
    command: ./bin/webpack-dev-server --host 0.0.0.0 --port 3035
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

  web:
    build: .
    volumes:
      - .:/var/www/app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - webpacker
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
