version: '3'
services:
  db:
    image: postgres:11-alpine
    ports:
      - '5432:5432'

  web:
    build: .
    command: flask run
    volumes:
      - .:/var/www/app
    ports:
      - '5000:5000'
    depends_on:
      - db
    environment:
      - FLASK_APP=app.py
