version: '3.7'
services:
  db:
    image: postgres:11-alpine
    restart: always
    ports:
      - '5432:5432'
  web:
    build: .
    volumes:
      - .:/var/www/app
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: bundle exec rails server -b 0.0.0.0 -p 3000
